# Generated by Django 2.2.17 on 2021-07-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_useraddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_address', models.CharField(max_length=1024)),
            ],
        ),
        migrations.DeleteModel(
            name='UserAddress',
        ),
    ]
