version: '3.7'

services:
  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod
    depends_on: 
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=capstone
      - POSTGRES_PASSWORD=123456789
      - POSTGRES_DB=capstone
  frontend:
    build: ./frontend
    command: npm start
    ports:
      - 3000:3000

volumes:
  postgres_data: