# Generated by Django 2.2.17 on 2021-07-13 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210713_1423'),
        ('store', '0002_auto_20210708_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='address_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.Address'),
        ),
    ]
